### PR TITLE
Adds basic python support

### PR DESCRIPTION
**Pull request by DuaneOBrien**
This is a first pass that should handle basic requirements.txt files for the purpose of providing some python support as outlined in #34 

* updates front end components to add Python to the list of supported files
* updates Upload component snapshots for testing
* creates requirements dependency manager and adds it to the list of managers
* adds Python to the supported languageTypes
* updates dependencies tests and associated test file

I'm unclear how the projects.json file is generated, but I tested locally by adding the following to projects.json at line 3012:

`      {
        "type": "requirements",
        "name": "babel"
      }
`

Screenshot below

Screen Shot 2019-10-04 at 9 24 00 PM

Marking this as a draft PR until we get a chance to discuss.

### CODE REVIEW

**Comment by znarf** [comment]
Looks great! Do you have an example GitHub profile (user or organization) that could be used to highlight that Python support is working?

**Comment by DuaneOBrien** [comment]
Looking in on projects.json again, I realized that you have python projects specified as type=pypi. I'll need to go back through and update my code to match before submitting.

I'll make those changes, and find a profile that can be used to demo Python support later this evening,.

**Comment by DuaneOBrien** [comment]
I've been able to confirm this with both local test requirements.txt files, and by referencing the following Owners/Organizations on GitHub:

https://github.com/codeforamerica
https://github.com/City-of-Helsinki/
https://github.com/uktrade/

**Comment by znarf** [comment]
@flickz can you review and merge if everything is good for you?

**Pull request merged**
