### PR TITLE
Prateekroopra upload package.json

### PR DESCRIPTION
**Pull request by prateekroopra**
Added Upload Package.JSON Component. Receiving Package.JSON file using Multer, checking for MIME type, uploading if the type is valid. I have written and commented the code for uploading the file to Amazon S3 using knox. I'm unsure of the use-case, if it is to be uploaded to S3, please uncomment the knox part and add a config file to it. 

Questions: Is the next step to re-direct the user to (the currently named) profile page and show RecommendationList and DependencyTable? If yes, please let me know, I can work on it. This is my first pull request to Open Collective repo, so I have sent very minimal amount of changes. PS: Great work!

### CODE REVIEW

**Comment by znarf** [comment]
Hi @prateekroopra  Thank you for your contribution! I added more information on the ticket, explaining what we have in mind for this feature. https://github.com/opencollective/backyourstack/issues/5

**Comment by prateekroopra** [comment]
Hi @znarf thank you! The description in #5 is really helpful. Will send a pull request soon. Cheers!

**Comment by znarf** [comment]
Hi @prateekroopra, I had some progress on the feature today: https://github.com/opencollective/backyourstack/pull/10

**Comment by prateekroopra** [comment]
Hi @znarf I'm about to check those changes out right now. I started implementing drop-zone today. I'll move to next sub-feature/requirement if you have included dropzone already in it. Thanks a lot for notifying!

**Comment by znarf** [comment]
Thank your for the PR, the same functionality was integrated in 
https://github.com/opencollective/backyourstack/pull/10

**Pull request closed without merging**
