### PR TITLE
Homepage redesign.

### PR DESCRIPTION
**Pull request by flickz**
This PR follows up #205 redesigns the homepage using the Figma design.

### Laptop Screenshot
Screenshot 2019-09-02 at 10 22 00 PM

### Mobile Screenshot
Screenshot 2019-09-02 at 10 22 52 PM

### CODE REVIEW

**Comment by znarf** [comment]
@flickz can you check the tests?

**Comment by flickz** [comment]
> the logo in the top bar looks the wrong size and misaligned

The actual size on the design is `211.76 x 48`, I used the `200 x 45`, I wasn't sure it would make obvious difference in look, I'll change that now.


> the icons in the footer are looking too big

The current size is similar to the design, `48 x 47.89` which looks like below:

Screenshot 2019-09-13 at 10 06 56 AM

Maybe I can reduce it to `30 x30` which would look like this:

Screenshot 2019-09-13 at 10 07 13 AM

What do you think?

**Comment by znarf** [comment]
@flickz If I look at Figma, this is what I see. 

https://www.figma.com/file/oNb9TlYCPcKABl4brBACDI/BYS.COM-XX1-%2F-Lab?node-id=0%3A1

Capture d’écran 2019-09-13 à 11 43 14

Compared to the current version.

Capture d’écran 2019-09-13 à 11 44 42

Why are we not seeing the same thing?

**Comment by flickz** [comment]
Oh I just realized I did not export the actual icons used in the figma design, I used the existing icons in the `img/`.

**Comment by flickz** [comment]
Screenshot 2019-09-13 at 2 13 49 PM

Better?

**Comment by znarf** [comment]
@flickz in the screenshot you shared, the icons are not aligned

**Comment by flickz** [comment]
Okay, 🙂  I think something is definitely wrong with my eyes at this point regarding alignments.

**Comment by flickz** [comment]
Screenshot 2019-09-13 at 2 37 04 PM

**Comment by znarf** [comment]
The top bar is still not fixed. It still looks like my screenshot at  https://github.com/opencollective/backyourstack/pull/206#issuecomment-530823464 can you check?

**Comment by znarf** [comment]
Be aware, I updated the copy on this branch.

**Comment by flickz** [comment]
@znarf Can you check it now?

**Comment by znarf** [comment]
It's really different from design. Why is that?

Screenshot 2019-09-13 at 17 49 22

**Comment by flickz** [comment]
Not surely exactly why because I tried to set the width and height to values from the figma design or maybe I should leave both out and let it be naturally as exported.

Doing that now, looks like below, does it look better?

Screenshot 2019-09-13 at 4 56 56 PM

**Comment by znarf** [comment]
It seems so. But it's better that you check by yourself that it matches the design. And double check on automated deployments that it looks good.

**Comment by flickz** [comment]
I also I think the extension shows a significant difference, I've been using svg exported file but this is png feels better I think.

Screenshot 2019-09-13 at 5 08 23 PM

**Comment by znarf** [comment]
I think it's a mistake to move out of SVG, this is our best shot for high definition devices and fallback flawlessly.

**Comment by flickz** [comment]
I think this feels better now

https://backyourstack-wqmxluescv.now.sh

**Comment by znarf** [comment]
@flickz the height is bigger than the design

Capture d’écran 2019-09-13 à 20 19 06

**Comment by flickz** [comment]
The actual height on figma is 80px, I've set it to that now.

**Comment by znarf** [comment]
Screenshot 2019-09-14 at 11 02 34

- the logo is not the same as design, look at the details in it
- the logo is 1px too high to the top
- also the height is 1px too much, look at the border on the bottom

**Comment by flickz** [comment]
> the logo is not the same as design, look at the details in it

I'm aware of the details from the logo and I think I've pointed out this might I've got something to do with the exported file format. Look at these 3 logos

#### Screenshot from figma directly
Screenshot 2019-09-14 at 6 26 19 PM

#### Screenshot of the logo as exported `svg` file
Screenshot 2019-09-14 at 6 25 28 PM

#### Screenshot of the logo as exported `png` file
Screenshot 2019-09-14 at 6 24 27 PM

Of course the `png` looks more accurate but blurry. The `svg` looks sharp but isn't accurate especially the symbol on the logo. Took away some cool background details in the logo. 

This was also the initial issue I had with the homepage background image, remember when you initially pointed out the background image looked weird and ugly on good screens, it was because of the `svg` format, I had to do a little trick of reducing the background opacity to make it look better. 

I've gone through figma documentation and I think their exported svg file has some features not supported. According to them, for `svg`,
> We do not export Background Blurs.

Which I think is the thing going on with the logos not matching. Here is their doc link
https://help.figma.com/article/206-export-settings

@znarf I'm really sorry this is taking longer than expected especially having to correct simple details I missed. I can't imagine how frustrating that must have been for you. I feel really bad at this point missing these little details but it has been helpful for me so far ahead of other design works to come. 

For the remaining 2 things on you listed, the logo top pixel and the top bar height, I've fixed it. Reduced both by 1px;

**Comment by znarf** [comment]
@flickz thank you for the explanations. Let's keep it as svg and ask the design team if they can export a high fidelity version for us.

@cuiki @raulgrafico can you help us exporting the BackYourStack logo so that it looks like in Figma? Because right now it seems it's missing some background blurs. See: https://github.com/opencollective/backyourstack/blob/design/homepage/src/static/img/backyourstack-logo.svg

**Pull request merged**
