### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by znarf**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/backyourstack ❤️

  What is done:
  - adding a badge to show the latest number of financial contributors
  - adding a banner displaying contributors to the project on GitHub
  - adding a banner displaying all individuals contributing financially on Open Collective
  - adding a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website

We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations. [[More info](https://github.com/opencollective/opencollective-postinstall)]

P.S: As with any pull request, feel free to comment or suggest changes.

  Thank you for your great contribution to the Open Source community. You are awesome! 🙌
  And welcome to the Open Collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other Open Source sustainers!

### CODE REVIEW

**Comment by piamancini** [comment]
>  Either you or a supporter signed this repository up for Open Collective

s/ 'supporter' with 'another core contributor'

> What is done:

s/ What it does:

>adding 

s/ adds 

postinstall: should we mention this is not compulsory?

**Comment by piamancini** [comment]
> postinstall: should we mention this is not compulsory?

How about: If you want to let people know you are receiving donations, we've also added a postinstall script you can use. [More info]

**Comment by znarf** [comment]
@piamancini uhm, doesn't make a huge difference with the current wording

**Comment by XVilka** [comment]
There are conflicts that should be resolved.

**Comment by znarf** [comment]
@XVilka I would be closing instead.

**Pull request closed without merging**
